# Generated by Django 5.0 on 2023-12-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_corta',
            field=models.CharField(default='Hola', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_larga',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción larga'),
        ),
    ]
