# Generated by Django 5.0 on 2023-12-12 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnologia_proyecto',
            name='id',
        ),
        migrations.AlterField(
            model_name='tecnologia_proyecto',
            name='tecnologia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.tecnologia'),
        ),
    ]
