# Generated by Django 5.0 on 2023-12-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_proyecto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion_corta',
            field=models.CharField(max_length=150),
        ),
    ]
