# Generated by Django 5.0 on 2023-12-14 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_proyecto_descripcion_corta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologia_proyecto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tecnologia_proyecto',
            name='tecnologia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tecnologia'),
        ),
    ]
