# Generated by Django 5.0 on 2023-12-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_proyecto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='sitio_web',
            field=models.CharField(null=True),
        ),
    ]
